### PR TITLE
Recommend latest version of ATC

### PR DESCRIPTION
**Pull request by ghost**
Addresses this criticism:

> Why recommend the most outdated version of Asrock Timing Configurator that is compatible for each platform and not just the latest version in general?

### CODE REVIEW

**Comment by integralfx** [comment]
You had to use the correct version for each platform for Asrock Timing Configurator to work

Does v4.0.14 work for all platforms?

**Comment by ghost** [comment]
Yes, of course. That is the purpose of the developer updating the application. I find it strange that anyone would think a developer would break backwards compatibility 🤔

**Comment by BoringBoredom** [comment]
> I find it strange that anyone would think a developer would break backwards compatibility 🤔

Because ATC tends to do exactly that. There is a reason this is mentioned in the guide.

**Comment by ghost** [comment]
I was not aware of this. What was the problem with newer ATC versions on old platforms? Misreported timings?

**Comment by integralfx** [comment]
> I was not aware of this. What was the problem with newer ATC versions on old platforms? Misreported timings?

It would either show an error message box saying that this platform is not supported or report the timings as the maximum value

**Pull request closed without merging**
